### ISSUE TITLE
Making selectors public

### ISSUE THREAD

**Issue by TheooJ** [skrub-data/skrub#1146]
In https://github.com/skrub-data/skrub/pull/1116, we discussed allowing users to use skrub selectors for the `cols` parameter. Selecting columns is very frequent in skrub transformers, and they might be useful for users. They are currently private, if we want to render them public, we need to:

- [ ] Document them. Their docstrings are already quite exhaustive but we need a dedicated example / reference in the doc
- [ ] Define for which parameters / transformers we allow selectors
- [ ] Support them in those cases (`Joiner`, `AggJoiner`, `MultiAggJoiner`, `SelectCols`, `DropCols`, `TableVectorizer`, etc)

**Comment by GaelVaroquaux** [comment]
I would like us to move forward with the recipe API first. I know that it is a big thing, but I think that it will help us understand the role and position of the selectors.
