### ISSUE TITLE
DOC Remove file-level flake8 noqa

### ISSUE THREAD

**Issue by Vincent-Maladiere** [skrub-data/skrub#755]
### Describe the issue linked to the documentation

The following files have a file-level noqa for flake8 E501, meaning that we don't check the length of lines in the docstrings —this is not a desired behavior, as we prefer having well-formatted docstrings.

- [ ] `skrub/_datetime_encoder.py`
- [x] `skrub/_deduplicate.py`
- [x] `skrub/_fuzzy_join.py`
- [x] `skrub/_minhash_encoder.py`
- [x] `skrub/_table_vectorizer.py`

To contribute to this meta-issue, you have to:

1. Select one of the files from the list above.
2. Remove the lines:
    ```python
    # Required for ignoring lines too long in the docstrings
	# flake8: noqa: E501
    ```
     and run `flake8 <name_of_the_file>` to see errors like:
    
    ```shell
    skrub/_datetime_encoder.py:40:89: E501 line too long (116 > 88 characters)
    ```
3. Fix the errors by formatting the docstring (e.g. breaking long lines into smaller lines).
4. Create a pull request for this file only
